# Computer set up and Introduction to the command line

This activity corresponds to Day 1 powerpoints available on Canvas. 

::: {.caution data=latex=""}
The first thing we need to do is make sure everyone can log onto the cluster. We will use the cluster for the rest of the activities in this course. 
:::


## Get oriented to the cluster

The first thing we will need to do is make an account. Everyone will need to set up an account [following these instructions.](https://www.youtube.com/watch?v=3kdW3EJS-OE) A member of the CU Research Computing staff will be on call to help us this afternoon. 

Watch [this video](https://www.youtube.com/watch?v=xfeRDnZQrJ4) to learn about the Alpine filesystem. 



::: {.learning data=latex=""}
If you would like more information on the cluster, please see the documentation on their website. You can also refer here if you need help during the course! 

[Overall Documentation](https://curc.readthedocs.io/en/latest/index.html)

[CURC Cheatsheet](https://curc.readthedocs.io/en/latest/additional-resources/CURC-cheatsheet.html)
:::

Now that we have accounts, let's log in! Go to the [OpenOnDemand site](https://ondemand.rc.colorado.edu/pun/sys/dashboard/), and use the menu at the top to access the Alpine Shell. 


## First command 

When you have accessed the Alpine shell, type `echo "Hello World!"`. The argument will be printed below your command. Congratulations, you've run your first command!  


## How to navigate a file system 

We will now familiarize ourselves with the file system. 

**1. List the contents of your project folder.**

```{cat, class.source='foldable'}
ls /projects/usrname/
```

**2. Make a new folder in `projects` called Day_1 and switch your location into that folder.**

```{cat, class.source='foldable'}
mkdir /projects/usrname/day_1
cd /projects/usrname/day_1
```

**3. What is the file path to this location?**

```{cat, class.source='foldable'}
pwd 
```

**4. What are the command options for ls?**

```{cat, class.source='foldable'}
ls --help
```



## Basic file manipulation 

**5. Copy the file `day1.txt` from our shared course folder to your `day_1` folder. **

All the files that you need to complete activities during this course will be found in this location.

```{cat, class.source='foldable'}
cp /scratch/alpine/mefr3284/ebio4100/day_1/day1.txt ./
```

**6. Rename the file to `day_1_original.txt`. **

```{cat, class.source='foldable'}

mv day1.txt day_1_original.txt

```

**7. Look at the whole file, then at just the first 5 lines, then at just the last 5 lines.**

```{cat, class.source='foldable'}

less day_1_original.txt

head -5 day_1_original.txt 

tail -n5 day_1_original.txt 

```

**8. Count the lines of the file that contain the word "apple."**

```{cat, class.source='foldable'}

wc -l day_1_original.txt

grep apple day_1_original.txt > day_1_apples.txt 

wc -l day_1_apples.txt 

grep [aA]pple day_1_original.txt | wc -l

```

**9. Replace all instances of the word "woodchuck" with "whistlepig". 

```{cat, class.source='foldable'}

sed 's/woodchuck/whistlepig/g' day_1_original.txt > day_1_mod.txt 

```


## Assignment

Write a command that makes a new file from `day_1_original.txt` that contains the first three lines with the word apple in them. Give the output file the name `yourlastname_day1.txt` and copy it to the shared folder `Assignments/Day1`. 


## If we have extra time... 

When running jobs on the cluster, we will typically use scripts. 

[Watch this video from CURC.](https://www.youtube.com/watch?v=dZLSEyYTiBM) 

Make a script in your `day_1` folder called `count_apples.sh`.  

Fill out the script using the command you created for the assignment. 

Run with with `sbatch count_apples.sh`.  

This will give you a job ID. Use that to run `sacct -j <job ID>`. 



